/**
 * Voice Lab catalogue — GENERATED by voice-agents/scripts/voice-lab-build.js.
 * Do not edit by hand; re-run the script instead.
 *
 * This module ships to the browser, so it carries NO provider name and NO
 * voice id. The label → vendor mapping lives in
 * voice-agents/docs/voice-lab-registry.json and stays out of the app.
 *
 * Generated: 2026-09-08T07:26:28.228Z
 */

export interface VoiceSample {
  /** Neutral public identifier, e.g. "FB-07". Stable across rebuilds. */
  label: string;
  lang: 'en' | 'es';
  /** null when the source library does not label it. */
  gender: 'female' | 'male' | null;
  accent: string;
  /** Short character description. Empty when the library ships none. */
  tone: string;
  /** Clean render. */
  studio: string;
  /** 8 kHz G.711 render — how the voice sounds on an actual phone call. */
  phone: string;
}

export const VOICE_SAMPLES: VoiceSample[] = [
  {
    "label": "FB-01",
    "lang": "en",
    "gender": "female",
    "accent": "American",
    "tone": "Young and popular, this playful American female voice is perfect for trendy content.",
    "studio": "/voice-lab/fb-01-studio.mp3",
    "phone": "/voice-lab/fb-01-phone.mp3"
  },
  {
    "label": "FB-02",
    "lang": "en",
    "gender": "female",
    "accent": "American",
    "tone": "Young adult woman with a confident and warm, mature quality and a reassuring, professional tone.",
    "studio": "/voice-lab/fb-02-studio.mp3",
    "phone": "/voice-lab/fb-02-phone.mp3"
  },
  {
    "label": "FB-03",
    "lang": "en",
    "gender": "female",
    "accent": "American",
    "tone": "This young adult female voice delivers sunny enthusiasm with a quirky attitude.",
    "studio": "/voice-lab/fb-03-studio.mp3",
    "phone": "/voice-lab/fb-03-phone.mp3"
  },
  {
    "label": "FB-04",
    "lang": "en",
    "gender": "female",
    "accent": "American",
    "tone": "This voice is warm, bright, and professional, characterized by a Standard American accent and a polished, narrative quality. It features a m.",
    "studio": "/voice-lab/fb-04-studio.mp3",
    "phone": "/voice-lab/fb-04-phone.mp3"
  },
  {
    "label": "FB-05",
    "lang": "en",
    "gender": "female",
    "accent": "American",
    "tone": "A professional woman with a pleasing alto pitch. Suitable for many use cases.",
    "studio": "/voice-lab/fb-05-studio.mp3",
    "phone": "/voice-lab/fb-05-phone.mp3"
  },
  {
    "label": "FB-06",
    "lang": "en",
    "gender": "female",
    "accent": "American",
    "tone": "Natural, Female, Adult, American, Professional.",
    "studio": "/voice-lab/fb-06-studio.mp3",
    "phone": "/voice-lab/fb-06-phone.mp3"
  },
  {
    "label": "FB-07",
    "lang": "en",
    "gender": "female",
    "accent": "American",
    "tone": "Natural, Female, Young, American, Friendly.",
    "studio": "/voice-lab/fb-07-studio.mp3",
    "phone": "/voice-lab/fb-07-phone.mp3"
  },
  {
    "label": "FB-08",
    "lang": "en",
    "gender": "female",
    "accent": "American",
    "tone": "Natural, Female, Young, American, Friendly.",
    "studio": "/voice-lab/fb-08-studio.mp3",
    "phone": "/voice-lab/fb-08-phone.mp3"
  },
  {
    "label": "FB-09",
    "lang": "en",
    "gender": "female",
    "accent": "Indian American",
    "tone": "Natural, Female, Young, Indian American, Friendly.",
    "studio": "/voice-lab/fb-09-studio.mp3",
    "phone": "/voice-lab/fb-09-phone.mp3"
  },
  {
    "label": "FB-10",
    "lang": "en",
    "gender": "female",
    "accent": "American",
    "tone": "Natural, Female, Young, American, Friendly.",
    "studio": "/voice-lab/fb-10-studio.mp3",
    "phone": "/voice-lab/fb-10-phone.mp3"
  }
];
